### ISSUE TITLE
MATLAB安装过程中出现的问题

### ISSUE THREAD

**Issue by 908164620** [leavesgrp/COPT-MATLAB#1]
你好，我在安装过程中遇到了以下问题：
在MATLAB中输入coptmex_install后显示：
Installing MATLAB interface for Cardinal Optimizer on Windows system...
Add and save path D:\MATLAB2021a\toolbox\COPT-MATLAB-master\COPT-MATLAB-master\lib to MATLAB search path.
不支持将脚本 copt_solve 作为函数执行:
D:\MATLAB2021a\toolbox\COPT-MATLAB-master\COPT-MATLAB-master\lib\copt_solve.m

出错 coptmex_install (第 24 行)
coptmex_ver = copt_solve();
请问这个要怎么解决呀？

**Comment by riis-hhd** [comment]
应该是你直接下载或者clone原代码。

直接下载master源码包，需要你自己编译后才能安装。

我们已经提供了预编译版本提供下载，请看REAMDE中的说明，或者下面链接中的最新release版本：
https://github.com/leavesgrp/COPT-MATLAB/releases

**Comment by 908164620** [comment]
我试了通过下载你给的这个网站里的最新release，然后通过matlab执行coptmex——install，然后输出了以下结果：

>> coptmex_install
Installing MATLAB interface for Cardinal Optimizer on Windows system...
Add and save path D:\COPT\copt-matlab.binary.r20220307\copt-matlab\lib to MATLAB search path.
MEX 文件 'D:\COPT\copt-matlab.binary.r20220307\copt-matlab\lib\copt_solve.mexw64' 无效: 找不到指定的程序。

出错 coptmex_install (第 24 行)
coptmex_ver = copt_solve();

这个是怎么回事呀？

**Comment by riis-hhd** [comment]
这里只是COPT和matlab的接口，需要先装好COPT才能调用copt_solve()。

然后COPT可以从下面网站申请免费的个人license，保证正确安装COPT后，再来使用matlab的接口。
https://shanshu.ai/copt
