### ISSUE TITLE
error with YALMIP and COPT solver

### ISSUE THREAD

**Issue by bigdataman2015** [leavesgrp/COPT-MATLAB#2]
% Set some options for YALMIP and solver
options = sdpsettings('verbose', 1, 'solver', 'COPT', 'debug', 1);  % error

**Comment by riis-hhd** [comment]
Sorry for late response. Can you explain a bit more about your purpose, or post pictures of error screen? 

On the other hand, copt-yalmip changes is just merged into develop branch of yalmip. Please update to latest version and retry.

**Comment by w4balance** [comment]
您好，我运行coptmex_install后，提示
Installing MATLAB interface for Cardinal Optimizer on Windows system...
Add and save path D:\Software\EE\COPT-MATLAB-R20230711\lib to MATLAB search path.
不支持将脚本 copt_solve 作为函数执行:
D:\Software\EE\COPT-MATLAB-R20230711\lib\copt_solve.m

请问对于这种情况有解决的方法吗，谢谢！我的MATLAB是2022b

**Comment by riis-hhd** [comment]
Please install binary version: [copt-matlab.binary.r20230711.zip](https://github.com/leavesgrp/COPT-MATLAB/releases/download/R20230711/copt-matlab.binary.r20230711.zip)

You might install it from source code package.
